---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bpfnfs.fullname" . }}
  labels:
    {{- include "bpfnfs.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bpfnfs.fullname" . }}
  labels:
    {{- include "bpfnfs.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bpfnfs.fullname" . }}
  labels:
    {{- include "bpfnfs.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "bpfnfs.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "bpfnfs.fullname" . }}
    namespace: {{ .Release.Namespace }}
